name: Minify JSON

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  minify-json:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Minify JSON files
        run: |
          for file in $(find . -type f -name "*.json"); do
            jq --indent 0 . "$file" > "$file.tmp" && mv "$file.tmp" "$file"
          done

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --staged --quiet || git commit -m "Minify JSON files [skip ci]"
          git push
